### ISSUE TITLE
Connect metamask failed(sometimes)

### ISSUE THREAD

**Issue by codepgq** [reown-com/reown_flutter#65]
**SDK Affected**

AppKit 

**Describe the bug**

On the simulator, calling the `openModalView()` method sometimes catches an unhandled exception
Linking metamask by scanning a QR code

**To Reproduce**

1. init 
```
Future<void> init(
    BuildContext context, {
    required String projectId,
    PairingMetadata? metadata,
  }) async {
    if (_appKit != null) return;
    final appKit = await ReownAppKit.createInstance(
      projectId: projectId,
      metadata: metadata ?? defaultMetadata,
    );

    _appKit = appKit;

    if (context.mounted) {
      _appKitModal = ReownAppKitModal(
        context: context,
        appKit: appKit,
      );

      await _appKitModal?.init();

      _listenSession();
      _listenModal();
      _listenRelayClient();
      debugPrint('default wallet connect init');
    } else {
      throw Exception('Context is not mounted');
    }
  }
```
2.  calling the `openModalView()`
```
  @override
  Future<void> connect() async {
    // With no options will open default screen depending on the connection status
    _appKitModal?.openModalView();
  }
```
3. Sometimes connect failed and show errors
```
flutter: onRelayClientMessage MessageEvent({"topic":"d4689aec4997d3704df131261e292531b244ed12945d397dd7994cb320a1617b","message":"AMuQCbSgaPUB1Kx0rCx92f0m993w5UgLQdiw/Et38dvMrXctPPjMZcZFeNyzoQMl2DE8emPIboZqLoCBemRWsXzDJ9R+SJjJVzGih3rXW7zspo62tw22e+Q4pc8M9Y1RyXeqSkiNNGhdjFxUfmJK/wXpHvGx3sDL3pkOExXCEdOy/O+TSGl77/N9YXLfnZ1TURo/9W6Q","publishedAt":1734876615026,"transportType":"relay"})
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: ReownCoreError(code: 2, message: No matching key. pairing topic doesn't exist: d4689aec4997d3704df131261e292531b244ed12945d397dd7994cb320a1617b, data: null)
#0      Pairing.isValidPairingTopic (package:reown_core/pairing/pairing.dart:384:7)
pairing.dart:384
#1      Pairing._isValidDisconnect (package:reown_core/pairing/pairing.dart:869:11)
pairing.dart:869
#2      Pairing._onPairingDeleteRequest (package:reown_core/pairing/pairing.dart:782:13)
pairing.dart:782
#3      Pairing._onMessageEvent (package:reown_core/pairing/pairing.dart:713:51)
pairing.dart:713
<asynchronous suspension>
```

**Expected behavior**

Connected metamask

**Smartphone (please complete the following information):**

 - Device: simulator(iPhone 16Plus)
 - OS: 18.1
 - Version: reown_appkit: ^1.2.0
 - Flutter version: 3.27.1
 ```
Flutter 3.27.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 17025dd882 (6 days ago) • 2024-12-17 03:23:09 +0900
Engine • revision cb4b5fff73
Tools • Dart 3.6.0 • DevTools 2.40.2
 ```

**Comment by quetool** [comment]
Can you share a complete reproducible code? I have the feeling you are recreating AppKit instance more times than needed.

**Comment by quetool** [comment]
Hello @codepgq , I'm closing this due to inactivity, feel free to reopen if this is still an issue.
