### ISSUE TITLE
Relay client connect throws `Bad state: Stream has already been listened to`

### ISSUE THREAD

**Issue by AlexV525** [reown-com/reown_flutter#66]
**SDK Affected**: WalletKit

**Describe the bug**

We got tons of reports in our production app.

<details>
<summary>Stack trace</summary>

```console
onRelayClientError: Bad state: Stream has already been listened to.
#0      _StreamController._subscribe (dart:async/stream_controller.dart:686)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:837)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:497)
#3      _CompleterStream.listen (package:async/src/stream_completer.dart:135)
#4      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114)
#5      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86)
#6      _ForwardingStream.listen (dart:async/stream_pipe.dart:81)
#7      CastStream.listen (dart:_internal/async_cast.dart:17)
#8      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114)
#9      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86)
#10     _ForwardingStream.listen (dart:async/stream_pipe.dart:81)
#11     _CloseGuaranteeStream.listen (package:stream_channel/src/close_guarantee_channel.dart:60)
#12     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114)
#13     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86)
#14     _ForwardingStream.listen (dart:async/stream_pipe.dart:81)
#15     _CloseGuaranteeStream.listen (package:stream_channel/src/close_guarantee_channel.dart:60)
#16     Peer.listen (package:reown_core/relay_client/json_rpc_2/src/peer.dart:123)
#17     RelayClient._createJsonRPCProvider (package:reown_core/relay_client/relay_client.dart:290)
<asynchronous suspension>
#18     RelayClient._connect (package:reown_core/relay_client/relay_client.dart:212)
<asynchronous suspension>
#19     RelayClient.connect (package:reown_core/relay_client/relay_client.dart:179)
<asynchronous suspension>
```

</details>

https://github.com/reown-com/reown_flutter/blob/3ffbfcede5e073e8d9d68a87faebf7bcd475c97a/packages/reown_core/lib/relay_client/json_rpc_2/src/peer.dart#L123

The `_stream` is only for a single subscription.

**To Reproduce**

Call the peer.listen multiple times would probably reproduce the issue.

**Comment by quetool** [comment]
Hello @AlexV525, can you share steps to reproduce this or some minimal reproducible code? We have no other reports about this from other devs/customers.
Furthermore, your PR is failing on integration tests, you can check by running `flutter test --dart-define=RELAY_ENDPOINT=wss://relay.walletconnect.org --dart-define=PROJECT_ID=cad4956f31a5e40a00b62865b030c6f8` inside `reown_core` package

**Comment by AlexV525** [comment]
> Hello @AlexV525, can you share steps to reproduce this or some minimal reproducible code? We have no other reports about this from other devs/customers.

From our timeline, this usually happens when the user has a poor network condition that might get stuck when connecting to the relay endpoint.

> Furthermore, your PR is failing on integration tests, you can check by running `flutter test --dart-define=RELAY_ENDPOINT=wss://relay.walletconnect.org --dart-define=PROJECT_ID=cad4956f31a5e40a00b62865b030c6f8` inside `reown_core` package

The PR has been updated. Would you like me to integrate it with the GitHub CI?

**Comment by quetool** [comment]
> The PR has been updated. Would you like me to integrate it with the GitHub CI?

No need, I just wanted you to check the tests, since this is the core package we are extra sensitive about it.

Thanks! I'll check it properly ASAP

**Comment by AlexV525** [comment]
> No need, I just wanted you to check the tests, since this is the core package we are extra sensitive about it.

After some looks I felt it would be good to integrate with.
